### ISSUE TITLE
Show Output Channel server option not working

### ISSUE THREAD

**Issue by Ridiculon** [redhat-developer/vscode-server-connector#482] opened 2021-02-22 15:12 UTC
Hi, in the last week or so the right-click option to show the output channel for a specific server seems to have stopped working. I am running a Wildfly 18 server and so far I've tried:
-restarting the server
-completely redeploying the server
-restarting the RSP provider
-recreating the server
-reloading VSCode
-restarting VSCode
-restarting my computer

Any help would be appreciated!

**Comment by robstryker** [comment] 2021-02-22 15:36
I'm not able to replicate this.  @odockal  are you able to?

**Comment by Ridiculon** [comment] 2021-02-22 15:54
This is the stderr i'm seeing, but i don't know if its related
![image](https://user-images.githubusercontent.com/1812965/108733256-f61e7c00-74f3-11eb-9b0d-d13bbf9fcd54.png)

**Comment by robstryker** [comment] 2021-02-22 16:59
This error is very common throughout the web (tomcat, felix, jira, and others) when using java 11. This output is just a warning and should not affect behavior at all. In future releases, java intends to error when this occurs, and we all expect that apache felix will fix their implementation to be complying by that time.

**Comment by odockal** [comment] 2021-02-23 07:16
@Ridiculon Thanks for reporting, If you start server, Output view just do not automatically pop ups, right? If so, have you tried to choose different output channel in drop down list on the right (referring to your image)? Server wildfly-18 should be there. Also, if there is a bug, it should show up in developers console (Help -> toggle developer tools -> Console) after the action is performed. Is there any error?

**Comment by Ridiculon** [comment] 2021-02-23 14:47
@odockal Correct, the Output shows like this on server start: 
![image](https://user-images.githubusercontent.com/1812965/108860071-7b1c9a80-75b3-11eb-8f8f-80c22c2e7120.png)

From there if I use the 'Show Output Channel' option nothing happens in either the Output or the dev tools console. So no bugs but also no console messages at all (even if i switch the console to 'verbose')

**Comment by robstryker** [comment] 2021-05-26 15:48
@odockal can you just verify if this is replicatable or not? Thanks.

**Comment by odockal** [comment] 2021-05-26 16:06
I tried today with vscode-server-connector 0.23.11 and vscode-rsp-ui 0.23.9 on VScode 1.56.0. I was able to call Show output channel on multiple occasion and it always showed the Output Tab and server output. All seems in a good shape. I cannot reproduce. 

P.S. I tried WF 18 and 22.

**Comment by robstryker** [comment] 2021-06-01 19:04
Closing as cannot replicate, sadly

**Closed by robstryker** 2021-06-01 19:04 UTC
